# Generated by Django 4.0.6 on 2022-07-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('table_time', models.CharField(max_length=20)),
                ('taken', models.BooleanField(default=False)),
            ],
        ),
    ]
