# Generated by Django 4.0.6 on 2022-07-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0006_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
