# Generated by Django 4.0.6 on 2022-07-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='PAYMENT',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='save_info',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_acc',
        ),
    ]
