# Generated by Django 4.0.6 on 2022-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0007_delete_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Local Delicacies', 'Local Delicacies'), ('Foriegn Delicacies', 'Foriegn Delicacies'), ('Medicinal Drinks', 'Medicinal Drinks'), ('Wines & Alcohol', 'Wines & Alcohol')], max_length=200),
        ),
    ]
